stages:
  - build
  - deploy

build-gitlab:
  stage: build
  script:
    - echo "Building docker container"
    - docker logout
    - docker build -t gitlab.the-qa-company.com:5050/d063520/hdtsparqlendpoint .
    - echo "Login to gitlab registry"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Pushing container to registry"
    - docker push $CI_REGISTRY/d063520/hdtsparqlendpoint
  only:
    - master

build-hub:
  stage: build
  script:
    - echo "Building docker container"
    - docker logout
    - docker build -t qacompany/hdt-query-service .
    - echo "Login to docker hub"
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - echo "Pushing container to registry"
    - docker push qacompany/hdt-query-service:latest
    - docker logout
  only:
    - master
  when: manual

deploy:
  stage: deploy
  image: maven:3.6-jdk-11
  script:
    - "cd hdt-qs-backend && mvn deploy -DskipTests -U -s ci_settings.xml"
  only:
    - master
