name: Task
description: Task to perform
labels: ["task"]
body:
    - type: checkboxes
      id: part
      attributes:
        label: Part of the endpoint? (leave empty if you don't know)
        description: Part of the endpoint? (leave empty if you don't know)
        options:
          - label: Backend (qendpoint-backend)
          - label: Store (qendpoint-backend)
          - label: Core (qendpoint-core)
          - label: Frontend (qendpoint-frontend)
          - label: Other
    - type: markdown
      attributes:
        value: |
          What needs to be done!
    - type: textarea
      attributes:
        label: Task to perform
        description: Description of the task
