name: Task
description: Task to perform
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        What needs to be done!
  - type: textarea
    attributes:
      label: Task to perform
      description: Description of the task
