name: Task
description: Task to perform
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        What needs to be done!
 - type: textarea
    attributes:
      label: Description of the task
      description: Small description of the task
      placeholder: |
        I need to ....
    validations:
      required: true
