name: Backend Tests

on:
  push:
    paths:
      - "qendpoint-core/**"

jobs:
  build:
    name: Compile and run tests (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn test
        working-directory: qendpoint-core
  build_window:
    name: Compile and run tests (Windows)
    runs-on: windows-latest
    needs: build
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn test
        working-directory: qendpoint-core

