name: Frontend Tests

on:
  push:
    paths:
      - "hdt-qs-frontend/**"

defaults:
  run:
    working-directory: hdt-qs-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: hdt-qs-frontend/package-lock.json
      - run: npm ci --legacy-peer-deps
      - name: Validate format
        run: npm run validate
      - name: Compiling
        run: npm run build --if-present
