name: Pull request Tests

on: [pull_request]

jobs:
  find_changes:
    name: Find changes
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.filter.outputs.core }}
      frontend: ${{ steps.filter.outputs.frontend }}
      endpoint: ${{ steps.filter.outputs.endpoint }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            core:
              - 'qendpoint-core/**'
            frontend:
              - 'hdt-qs-frontend/**'
            endpoint:
              - 'hdt-qs-backend/**'
  build_core:
    name: Core (Linux)
    needs: find_changes
    if: needs.find_changes.outputs.core == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build tools
        run: mvn install -DskipTests
      - name: Validate format
        run: mvn -B formatter:validate
        working-directory: qendpoint-core
      - name: Run tests
        run: mvn -B -U clean install -Dmaven.javadoc.skip=true -DskipTests
        working-directory: qendpoint-core
      - name: Test
        run: mvn -B clean test -Dmaven.javadoc.skip=true
        working-directory: qendpoint-core
  build_core_window:
    name: Core (Windows)
    runs-on: windows-latest
    needs:
      - build_core
      - find_changes
    if: needs.find_changes.outputs.core == 'true'
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Validate format
        run: mvn -B formatter:validate
        working-directory: qendpoint-core
      - name: Run tests
        run: mvn -B -U clean install -Dmaven.javadoc.skip=true -DskipTests
      - name: Test
        run: mvn -B clean test -Dmaven.javadoc.skip=true
        working-directory: qendpoint-core

  build_endpoint:
    name: Endpoint (Linux)
    runs-on: ubuntu-latest
    needs:
      - find_changes
    if: needs.find_changes.outputs.endpoint == 'true'
    strategy:
      matrix:
        jdk: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Validate format
        run: mvn -B formatter:validate
        working-directory: hdt-qs-backend
      - name: Run tests
        run: mvn -B -U clean install -Dmaven.javadoc.skip=true -DskipTests
      - name: Test
        run: mvn -B clean test -Dmaven.javadoc.skip=true
        working-directory: hdt-qs-backend
  build_endpoint_window:
    name: Endpoint (Windows)
    runs-on: windows-latest
    needs:
      - build_endpoint
      - find_changes
    if: needs.find_changes.outputs.endpoint == 'true'
    strategy:
      matrix:
        jdk: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Validate format
        run: mvn -B formatter:validate
        working-directory: hdt-qs-backend
      - name: Run tests
        run: mvn -B -U clean install -Dmaven.javadoc.skip=true -DskipTests
      - name: Test
        run: mvn -B clean test -Dmaven.javadoc.skip=true
        working-directory: hdt-qs-backend
  build_frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs:
      - find_changes
    if: needs.find_changes.outputs.frontend == 'true'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: hdt-qs-frontend/package-lock.json
      - run: npm ci --legacy-peer-deps
        working-directory: hdt-qs-frontend
      - name: Validate format
        run: npm run validate
        working-directory: hdt-qs-frontend
      - name: Compiling
        run: npm run build --if-present
        working-directory: hdt-qs-frontend