name: Pull request Tests Backend

on:
  pull_request:
    paths:
      - "hdt-qs-backend/**"

jobs:
  build:
    name: Compile and run tests (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-
      - name: Build tools
        run: mvn install -DskipTests
      - name: Validate format
        run: mvn -B formatter:validate
        working-directory: hdt-qs-backend
      - name: Compiling
        run: mvn -B -U clean install -Dmaven.javadoc.skip=true -DskipTests
        working-directory: hdt-qs-backend
      - name: Test
        run: mvn -B clean test -Dmaven.javadoc.skip=true
        working-directory: hdt-qs-backend
  build_windows:
    name: Compile and run tests (Windows)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk${{ matrix.jdk }}-maven-
      - name: Validate format
        run: mvn -B formatter:validate
        working-directory: hdt-qs-backend
      - name: Compiling
        run: mvn -B -U clean install -Dmaven.javadoc.skip=true -DskipTests
        working-directory: hdt-qs-backend
      - name: Test
        run: mvn -B clean test -Dmaven.javadoc.skip=true
        working-directory: hdt-qs-backend
