name: Build and Sign macOS
on:
  push:
    tags:
      - '*'
defaults:
  run:
    working-directory: hdt-qs-backend
jobs:
  macos:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: package
        run: mvn clean package -DskipTests
      - name: Codesign executable
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 —decode > certificate.p12
          security create-keychain -p your-password build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p your-password build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security find-identity -v
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k your-password build.keychain
          /usr/bin/codesign --force -s <identity-id> ./path/to/you/app -v
	# We will fill this part shortly
